package com.example.choquality.common.spec

import lombok.Getter

@Getter
enum class SDKSpec(val code: Int, val message: String) {
    SUCCESS(0, "SUCCESS"),
    FAIL_JWT_INIT(1, "JWT_INIT_FAILED"),
    JWT_EXPIRED(2, "JWT_EXPIRED"),
    FAIL_JWT_VALID(3, "JWT_VALID_FAIL"),
    FAIL_LOGIN(4, "LOGIN_FAIL"),
    FAIL_SIGNUP(5, "FAIL_SIGNUP"),
    FAIL_PUT(6, "FAIL_PUT"),
    FAIL_GET(7, "FAIL_GET"),
    FAIL_DELETE(8, "FAIL_DELETE"),
    FAIL_DELETE_USER(9, "FAIL_DELETE_USER"),
    FAIL_TODO_CREATE(10, "FAIL_TODO_CREATE"),
    FAIL_TODO_UPDATE(11, "FAIL_TODO_UPDATE"),
    FAIL_TODO_GET(12, "FAIL_TODO_GET"),
    FAIL_TODO_DELETE(13, "FAIL_TODO_DELETE"),
    FAIL_PARAM(99, "FAIL_PARAM"),
    FAIL_DB_PROCESS(999, "FAIL_DB_PROCESS")
}
